"""B7 — Memory Store (local JSON; the "mem0" upgrade slots in later).

Two things persist across sessions inside the project (`data/sessions/`):

1. resume_position  — where playback should restart next time.
2. session_summaries — short notes about what the listener discussed, so the
   narrator keeps continuity ("earlier you asked about ..."). Summaries are
   generated by the local LLM at session end and capped to the last N, so the
   context handed back stays small and cheap.

Full per-session transcripts are also written for debugging.
"""
from __future__ import annotations

import json
import time
from dataclasses import dataclass, field

from . import config, llm
from .position import PlaybackPosition

_LONGTERM = config.SESSIONS_DIR / "memory.json"
_MAX_SUMMARIES = 6          # keep the last N session summaries
_SUMMARIES_IN_CONTEXT = 3   # how many to feed into a new session
_MAX_ITEMS = 300            # cap embedded memory items (WS-8)
_RECALL_K = 3               # semantic hits injected per turn


def _load_longterm() -> dict:
    if _LONGTERM.exists():
        try:
            d = json.loads(_LONGTERM.read_text(encoding="utf-8"))
            d.setdefault("items", [])
            return d
        except json.JSONDecodeError:
            pass
    return {"resume_position": None, "session_summaries": [], "items": []}


def _save_longterm(d: dict) -> None:
    config.SESSIONS_DIR.mkdir(parents=True, exist_ok=True)
    _LONGTERM.write_text(json.dumps(d, indent=2), encoding="utf-8")


def get_resume_position() -> PlaybackPosition | None:
    if config.FRESH:
        return None
    rp = _load_longterm().get("resume_position")
    if rp:
        return PlaybackPosition(int(rp["chapter_index"]), float(rp["position_sec"]))
    return None


def set_resume_position(pos: PlaybackPosition) -> None:
    d = _load_longterm()
    d["resume_position"] = {
        "chapter_index": pos.chapter_index,
        "position_sec": pos.position_sec,
    }
    _save_longterm(d)


def recent_context(n: int = _SUMMARIES_IN_CONTEXT) -> str:
    """Compact prior-session context to prepend to a new session (or '')."""
    if config.FRESH:
        return ""
    summaries = _load_longterm().get("session_summaries", [])[-n:]
    if not summaries:
        return ""
    lines = [f"- {s['summary']}" for s in summaries]
    return "Notes from earlier sessions with this listener:\n" + "\n".join(lines)


# ── WS-8: semantic cross-session recall (local embeddings) ─────────────────────
def _cosine(a: list[float], b: list[float]) -> float:
    import math

    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a)) or 1.0
    nb = math.sqrt(sum(y * y for y in b)) or 1.0
    return dot / (na * nb)


def _store_items(texts: list[str]) -> None:
    """Embed and append memory items (best-effort; silent if embeddings are down)."""
    texts = [t.strip() for t in texts if t and t.strip()]
    if not texts:
        return
    try:
        embs = llm.embed(texts)
    except llm.LLMError:
        return
    d = _load_longterm()
    now = time.time()
    for t, e in zip(texts, embs):
        d["items"].append({"text": t, "ts": now, "emb": e})
    d["items"] = d["items"][-_MAX_ITEMS:]
    _save_longterm(d)


def semantic_recall(query: str, k: int = _RECALL_K) -> list[str]:
    """Return up to k past memory items most relevant to `query` (or [])."""
    d = _load_longterm()
    items = d.get("items", [])
    if not items or not query.strip():
        return []
    try:
        q = llm.embed([query])[0]
    except llm.LLMError:
        return []
    scored = sorted(items, key=lambda it: _cosine(q, it.get("emb", [])), reverse=True)
    return [it["text"] for it in scored[:k]]


def turn_context(query: str) -> str:
    """Per-turn memory block: recent-session continuity + semantic hits for this query."""
    if config.FRESH:
        return ""
    parts = []
    recent = recent_context()
    if recent:
        parts.append(recent)
    hits = semantic_recall(query)
    if hits:
        parts.append("Relevant things this listener said before:\n" + "\n".join(f"- {h}" for h in hits))
    return "\n\n".join(parts)


@dataclass
class SessionLog:
    """Collects one session's turns; summarizes + persists on end()."""

    turns: list[dict] = field(default_factory=list)
    started: float = field(default_factory=time.time)

    def add(self, role: str, text: str) -> None:
        self.turns.append({"role": role, "text": text})

    def _write_transcript(self) -> None:
        config.SESSIONS_DIR.mkdir(parents=True, exist_ok=True)
        ts = time.strftime("%Y%m%d-%H%M%S", time.localtime(self.started))
        path = config.SESSIONS_DIR / f"session-{ts}.json"
        path.write_text(
            json.dumps({"started": self.started, "turns": self.turns}, indent=2),
            encoding="utf-8",
        )

    def _summarize(self) -> str:
        convo = "\n".join(f"{t['role']}: {t['text']}" for t in self.turns)
        system = (
            "Summarize, in 1-2 sentences, what the listener asked about or preferred "
            "in this audiobook conversation, as a note to your future self. Focus on "
            "their interests and any requests; do NOT include story spoilers. Plain text only."
        )
        try:
            return llm.chat(
                [
                    {"role": "system", "content": system},
                    {"role": "user", "content": convo},
                ],
                temperature=0.2,
                num_predict=120,
            ).strip()
        except llm.LLMError:
            # Fall back to a trivial summary if the model is unavailable.
            asks = [t["text"] for t in self.turns if t["role"] == "listener"]
            return "Listener asked: " + "; ".join(asks[:4]) if asks else ""

    def end(self, resume_pos: PlaybackPosition | None = None) -> None:
        if config.FRESH:
            return  # fresh session: persist nothing (memory/history left untouched)
        if not self.turns and resume_pos is None:
            return
        self._write_transcript()
        d = _load_longterm()
        summary = self._summarize() if self.turns else ""
        if summary:
            d.setdefault("session_summaries", []).append(
                {"ts": self.started, "summary": summary}
            )
            d["session_summaries"] = d["session_summaries"][-_MAX_SUMMARIES:]
        if resume_pos is not None:
            d["resume_position"] = {
                "chapter_index": resume_pos.chapter_index,
                "position_sec": resume_pos.position_sec,
            }
        _save_longterm(d)
        # WS-8: embed this session's listener asks + summary for future semantic recall.
        asks = [t["text"] for t in self.turns if t["role"] == "listener"]
        _store_items(asks + ([summary] if summary else []))
